#!/bin/sh

# This file has been generated automatically. It is a generic wrapper
# responsible for launching a Crosswalk-based application.

which xwalk 2>&1 > /dev/null

if [ $? -ne 0 ]; then
    echo "Error: cannot find the 'xwalk' executable."
    echo "Please make sure Crosswalk is installed."
    exit 1
fi

BASEDIR=$(dirname `readlink -f "$0"`)
MANIFEST="${BASEDIR}/www/manifest.json"

if [ ! -f "${MANIFEST}" ]; then
    echo "Error: Cannot find ${MANIFEST}."
    echo "Plase make sure the application has been installed correctly."
    exit 1
fi

exec xwalk "${BASEDIR}/www/manifest.json"
