#!/bin/bash

# Copyright © 2014 Intel Corporation. All rights reserved.
# Use  of this  source  code is  governed by  an Apache v2
# license that can be found in the LICENSE-APACHE-V2 file.

CMD_PATH=$( realpath "$0" )
DIR=$( cd "$( dirname "$CMD_PATH" )" && pwd )
XWALK=$( which xwalk )

$XWALK ${DIR}/www/manifest.json

